// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/hubspot-conversations-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"channel | conversations_batch_response_public_actor | conversations_collection_response_public_message_forward_paging | conversations_collection_response_public_thread_forward_paging | conversations_collection_response_with_total_public_channel | conversations_collection_response_with_total_public_channel_account | conversations_collection_response_with_total_public_inbox | conversations_inbox_messages_batch_response_public_actor | conversations_inbox_messages_collection_response_public_message | conversations_inbox_messages_collection_response_public_thread | conversations_inbox_messages_collection_response_with_total_public | conversations_inbox_messages_collection_response_with_total_public2 | conversations_inbox_messages_collection_response_with_total_public3 | conversations_inbox_messages_public_actor | conversations_inbox_messages_public_channel | conversations_inbox_messages_public_channel_account | conversations_inbox_messages_public_inbox | conversations_inbox_messages_public_message | conversations_inbox_messages_public_message_content | conversations_inbox_messages_public_thread | conversations_public_actor | conversations_public_channel | conversations_public_channel_account | conversations_public_inbox | conversations_public_message | conversations_public_message_content | conversations_public_thread | custom_channels_collection_response_with_total_public_channel | custom_channels_collection_response_with_total_public_channel2 | custom_channels_public_channel_account | custom_channels_public_channel_account_staging_token | custom_channels_public_channel_integration_channel | custom_channels_public_conversations_message | public_thread | thread | visitor_identification_identification_token"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.HubspotConversationsSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "hubspot-conversations_list",
		Description: "List records from HubspotConversations. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "hubspot-conversations_load",
		Description: "Load a single record from HubspotConversations. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.HubspotConversationsSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.HubspotConversationsSDK, name string) (sdk.HubspotConversationsEntity, error) {
	switch strings.ToLower(name) {
	case "channel":
		return client.Channel(nil), nil
	case "conversations_batch_response_public_actor":
		return client.ConversationsBatchResponsePublicActor(nil), nil
	case "conversations_collection_response_public_message_forward_paging":
		return client.ConversationsCollectionResponsePublicMessageForwardPaging(nil), nil
	case "conversations_collection_response_public_thread_forward_paging":
		return client.ConversationsCollectionResponsePublicThreadForwardPaging(nil), nil
	case "conversations_collection_response_with_total_public_channel":
		return client.ConversationsCollectionResponseWithTotalPublicChannel(nil), nil
	case "conversations_collection_response_with_total_public_channel_account":
		return client.ConversationsCollectionResponseWithTotalPublicChannelAccount(nil), nil
	case "conversations_collection_response_with_total_public_inbox":
		return client.ConversationsCollectionResponseWithTotalPublicInbox(nil), nil
	case "conversations_inbox_messages_batch_response_public_actor":
		return client.ConversationsInboxMessagesBatchResponsePublicActor(nil), nil
	case "conversations_inbox_messages_collection_response_public_message":
		return client.ConversationsInboxMessagesCollectionResponsePublicMessage(nil), nil
	case "conversations_inbox_messages_collection_response_public_thread":
		return client.ConversationsInboxMessagesCollectionResponsePublicThread(nil), nil
	case "conversations_inbox_messages_collection_response_with_total_public":
		return client.ConversationsInboxMessagesCollectionResponseWithTotalPublic(nil), nil
	case "conversations_inbox_messages_collection_response_with_total_public2":
		return client.ConversationsInboxMessagesCollectionResponseWithTotalPublic2(nil), nil
	case "conversations_inbox_messages_collection_response_with_total_public3":
		return client.ConversationsInboxMessagesCollectionResponseWithTotalPublic3(nil), nil
	case "conversations_inbox_messages_public_actor":
		return client.ConversationsInboxMessagesPublicActor(nil), nil
	case "conversations_inbox_messages_public_channel":
		return client.ConversationsInboxMessagesPublicChannel(nil), nil
	case "conversations_inbox_messages_public_channel_account":
		return client.ConversationsInboxMessagesPublicChannelAccount(nil), nil
	case "conversations_inbox_messages_public_inbox":
		return client.ConversationsInboxMessagesPublicInbox(nil), nil
	case "conversations_inbox_messages_public_message":
		return client.ConversationsInboxMessagesPublicMessage(nil), nil
	case "conversations_inbox_messages_public_message_content":
		return client.ConversationsInboxMessagesPublicMessageContent(nil), nil
	case "conversations_inbox_messages_public_thread":
		return client.ConversationsInboxMessagesPublicThread(nil), nil
	case "conversations_public_actor":
		return client.ConversationsPublicActor(nil), nil
	case "conversations_public_channel":
		return client.ConversationsPublicChannel(nil), nil
	case "conversations_public_channel_account":
		return client.ConversationsPublicChannelAccount(nil), nil
	case "conversations_public_inbox":
		return client.ConversationsPublicInbox(nil), nil
	case "conversations_public_message":
		return client.ConversationsPublicMessage(nil), nil
	case "conversations_public_message_content":
		return client.ConversationsPublicMessageContent(nil), nil
	case "conversations_public_thread":
		return client.ConversationsPublicThread(nil), nil
	case "custom_channels_collection_response_with_total_public_channel":
		return client.CustomChannelsCollectionResponseWithTotalPublicChannel(nil), nil
	case "custom_channels_collection_response_with_total_public_channel2":
		return client.CustomChannelsCollectionResponseWithTotalPublicChannel2(nil), nil
	case "custom_channels_public_channel_account":
		return client.CustomChannelsPublicChannelAccount(nil), nil
	case "custom_channels_public_channel_account_staging_token":
		return client.CustomChannelsPublicChannelAccountStagingToken(nil), nil
	case "custom_channels_public_channel_integration_channel":
		return client.CustomChannelsPublicChannelIntegrationChannel(nil), nil
	case "custom_channels_public_conversations_message":
		return client.CustomChannelsPublicConversationsMessage(nil), nil
	case "public_thread":
		return client.PublicThread(nil), nil
	case "thread":
		return client.Thread(nil), nil
	case "visitor_identification_identification_token":
		return client.VisitorIdentificationIdentificationToken(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
